---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Populate service facts
      service_facts:

    - name: Check haproxy service
      assert:
        that:
          - ansible_facts.services['haproxy.service'].state == "running"
          - ansible_facts.services['haproxy.service'].status == "enabled"
...